[2022-05-10 18:11:10,100] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-10T18:10:00.992820+00:00 [queued]>
[2022-05-10 18:11:10,110] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-10T18:10:00.992820+00:00 [queued]>
[2022-05-10 18:11:10,111] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-10 18:11:10,111] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-10 18:11:10,112] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-10 18:11:10,245] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-05-10 18:10:00.992820+00:00
[2022-05-10 18:11:10,251] {standard_task_runner.py:52} INFO - Started process 265 to run task
[2022-05-10 18:11:10,255] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Smart_ETL_Tool', 'extract', 'manual__2022-05-10T18:10:00.992820+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/etl_exemple.py', '--cfg-path', '/tmp/tmp9c6th25q', '--error-file', '/tmp/tmp4h1c4y82']
[2022-05-10 18:11:10,256] {standard_task_runner.py:80} INFO - Job 106: Subtask extract
[2022-05-10 18:11:10,504] {logging_mixin.py:109} INFO - Running <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-10T18:10:00.992820+00:00 [running]> on host 0b2ea813f779
[2022-05-10 18:11:11,935] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Smart_ETL_Tool
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-05-10T18:10:00.992820+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-10T18:10:00.992820+00:00
[2022-05-10 18:11:11,936] {logging_mixin.py:109} INFO - done
[2022-05-10 18:11:11,937] {logging_mixin.py:109} INFO - <***.providers.mysql.hooks.mysql.MySqlHook object at 0x7fa5ae72a510>
[2022-05-10 18:11:11,995] {base.py:79} INFO - Using connection to: id: postgres1_db. Host: docker.host.internal, Port: 5433, Schema: classicmodels, Login: postgres, Password: ***, extra: {}
[2022-05-10 18:11:26,862] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_exemple.py", line 61, in extract
    df = hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 137, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 166, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host 'docker.host.internal' (-3)")
[2022-05-10 18:11:29,542] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=Smart_ETL_Tool, task_id=extract, execution_date=20220510T181000, start_date=20220510T181110, end_date=20220510T181129
[2022-05-10 18:11:32,477] {standard_task_runner.py:98} ERROR - Failed to execute job 106 for task extract ((2005, "Unknown MySQL server host 'docker.host.internal' (-3)"); 265)
[2022-05-10 18:11:32,603] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-10 18:11:34,046] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
