[2022-05-05 18:55:00,010] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T18:54:28.887591+00:00 [queued]>
[2022-05-05 18:55:00,035] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T18:54:28.887591+00:00 [queued]>
[2022-05-05 18:55:00,036] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-05 18:55:00,037] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-05 18:55:00,037] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-05 18:55:00,375] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-05-05 18:54:28.887591+00:00
[2022-05-05 18:55:00,391] {standard_task_runner.py:52} INFO - Started process 274 to run task
[2022-05-05 18:55:00,406] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Smart_ETL_Tool', 'extract', 'manual__2022-05-05T18:54:28.887591+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/etl_exemple.py', '--cfg-path', '/tmp/tmpfsp1kjmo', '--error-file', '/tmp/tmpf3ks2k62']
[2022-05-05 18:55:00,411] {standard_task_runner.py:80} INFO - Job 86: Subtask extract
[2022-05-05 18:55:00,852] {logging_mixin.py:109} INFO - Running <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T18:54:28.887591+00:00 [running]> on host 70e1e4d83c3a
[2022-05-05 18:55:01,883] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Smart_ETL_Tool
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-05-05T18:54:28.887591+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-05T18:54:28.887591+00:00
[2022-05-05 18:55:01,885] {logging_mixin.py:109} INFO - done
[2022-05-05 18:55:01,886] {logging_mixin.py:109} INFO - <***.providers.mysql.hooks.mysql.MySqlHook object at 0x7f03701c0790>
[2022-05-05 18:55:02,242] {base.py:79} INFO - Using connection to: id: mysql_db. Host: 127.0.0.1, Port: 3306, Schema: classicmodels, Login: houssem, Password: ***, extra: {}
[2022-05-05 18:55:04,496] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_exemple.py", line 61, in extract
    df = hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 137, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 166, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)")
[2022-05-05 18:55:04,538] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=Smart_ETL_Tool, task_id=extract, execution_date=20220505T185428, start_date=20220505T185500, end_date=20220505T185504
[2022-05-05 18:55:05,716] {standard_task_runner.py:98} ERROR - Failed to execute job 86 for task extract ((2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)"); 274)
[2022-05-05 18:55:05,795] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-05 18:55:06,710] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
