[2022-05-10 19:11:50,023] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-10T19:09:43.888213+00:00 [queued]>
[2022-05-10 19:11:50,103] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-10T19:09:43.888213+00:00 [queued]>
[2022-05-10 19:11:50,104] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-10 19:11:50,104] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-10 19:11:50,105] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-10 19:11:50,517] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-05-10 19:09:43.888213+00:00
[2022-05-10 19:11:50,526] {standard_task_runner.py:52} INFO - Started process 1910 to run task
[2022-05-10 19:11:50,530] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Smart_ETL_Tool', 'extract', 'manual__2022-05-10T19:09:43.888213+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/etl_exemple.py', '--cfg-path', '/tmp/tmpyqwezbs5', '--error-file', '/tmp/tmpejqa2cfh']
[2022-05-10 19:11:50,532] {standard_task_runner.py:80} INFO - Job 111: Subtask extract
[2022-05-10 19:11:50,988] {logging_mixin.py:109} INFO - Running <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-10T19:09:43.888213+00:00 [running]> on host 0b2ea813f779
[2022-05-10 19:11:51,381] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Smart_ETL_Tool
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-05-10T19:09:43.888213+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-10T19:09:43.888213+00:00
[2022-05-10 19:11:51,383] {logging_mixin.py:109} INFO - done
[2022-05-10 19:11:51,384] {logging_mixin.py:109} INFO - <***.providers.postgres.hooks.postgres.PostgresHook object at 0x7fa5ae320410>
[2022-05-10 19:11:51,398] {base.py:79} INFO - Using connection to: id: postgres1_db. Host: localhost, Port: 5433, Schema: classicmodels, Login: postgres, Password: ***, extra: {}
[2022-05-10 19:11:51,400] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_exemple.py", line 61, in extract
    df = hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 137, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2022-05-10 19:11:51,500] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=Smart_ETL_Tool, task_id=extract, execution_date=20220510T190943, start_date=20220510T191150, end_date=20220510T191151
[2022-05-10 19:11:51,658] {standard_task_runner.py:98} ERROR - Failed to execute job 111 for task extract (connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 1910)
[2022-05-10 19:11:51,752] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-10 19:11:51,917] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
